const KEY='rent-state-v1',APP_VERSION=5,MONTHS=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],SERVICE_TYPES=[['maintenance','Mantto','🧾'],['club','Casa Club','🏡']],CATS={contract:'Contrato',receipt:'Comprobante',identification:'Identificación',other:'Otro'};
const contractDefaults={propertyName:'Mi departamento',propertyLocation:'',currency:'MXN',rentAmount:0,maintenanceAmount:0,clubAmount:0,rentDueDay:15,rentGraceDays:0,moratoryInterestPercent:0,serviceDueDay:0,tenantName:'Nuevo inquilino',tenantEmail:'',tenantPhone:'',contractSigned:'',contractStart:'',contractEnd:'',depositAmount:0,depositPaid:false,depositDate:'',firstPaymentAmount:0,firstPaymentDue:'',promissoryCount:11,adminFeeAmount:0,adminFeePaid:false,adminFeeDate:'',adminFeeNote:'Cuota administrativa pendiente'};
const seed=()=>({schemaVersion:APP_VERSION,selectedMonth:new Date().toISOString().slice(0,7),settings:{...contractDefaults},payments:[],notes:{},legacy:['2025-04','2025-05','2025-06','2025-07','2025-08','2025-09','2025-10','2025-11','2025-12','2026-01','2026-02','2026-03','2026-04','2026-05','2026-06','2026-07']});
function loadState(){try{let p=JSON.parse(localStorage.getItem(KEY));if(!p)return seed();let base=seed(),out={...base,...p,settings:{...base.settings,...(p.settings||{})},notes:{...base.notes,...(p.notes||{})}};if((out.schemaVersion||1)<5){if(out.settings.promissoryCount==null)out.settings.promissoryCount=11;if(out.settings.serviceDueDay==null)out.settings.serviceDueDay=0;if(out.settings.moratoryInterestPercent==null)out.settings.moratoryInterestPercent=0;out.schemaVersion=5}localStorage.setItem(KEY,JSON.stringify(out));return out}catch{return seed()}}
let state=loadState(),histYear=Number(state.selectedMonth?.slice(0,4))||new Date().getFullYear(),docFilter='all',deferredPrompt;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n||0)),fmt=v=>v?new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short',year:'numeric'}).format(new Date(v+'T12:00:00')):'—';
function toast(t){let e=document.getElementById('toast');e.textContent=t;e.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display='none',2200)}
function monthLabel(k){let[y,m]=k.split('-').map(Number);return MONTHS[m-1]+' '+y}function shift(k,d){let[y,m]=k.split('-').map(Number);m+=d;while(m<1){m+=12;y--}while(m>12){m-=12;y++}return y+'-'+String(m).padStart(2,'0')}
function pay(k,t){return state.payments.find(p=>p.month===k&&p.type===t)}function rentStatus(k){if(pay(k,'rent'))return'paid';if(state.legacy.includes(k))return'legacy';return'pending'}function serviceAmount(t){return Number(t==='maintenance'?state.settings.maintenanceAmount:state.settings.clubAmount)||0}function serviceStatus(k,t){if(pay(k,t))return'paid';if(!serviceAmount(t))return'unconfigured';return'pending'}function servicesDone(k){return SERVICE_TYPES.filter(([t])=>serviceStatus(k,t)==='paid').length}function servicesPending(k){return SERVICE_TYPES.reduce((a,[t])=>a+(serviceStatus(k,t)==='pending'?serviceAmount(t):0),0)}
function noteDates(){let s=state.settings;if(!s.contractStart)return[];let [y,m]=s.contractStart.slice(0,7).split('-').map(Number),day=Number(s.rentDueDay||15),count=Number(s.promissoryCount||11),a=[];for(let i=1;i<=count;i++){let mm=m+i,yy=y+Math.floor((mm-1)/12),mo=((mm-1)%12)+1;a.push(`${yy}-${String(mo).padStart(2,'0')}-${String(day).padStart(2,'0')}`)}return a}
function contractLastRentMonth(){let a=noteDates();return a.length?a[a.length-1].slice(0,7):(state.settings.contractStart||'').slice(0,7)}function isContractMonth(k){let start=(state.settings.contractStart||'').slice(0,7),end=contractLastRentMonth();return !!start&&k>=start&&k<=end}function noteIndex(k){return noteDates().findIndex(d=>d.slice(0,7)===k)}
function firstRentMonth(){return (state.settings.contractStart||'').slice(0,7)}function firstPaymentPaid(){let k=firstRentMonth();return !!k&&rentStatus(k)==='paid'&&state.settings.depositPaid}function receivable(k){let first=firstRentMonth();if(k===first&&!firstPaymentPaid())return Number(state.settings.firstPaymentAmount||0);if(isContractMonth(k)&&rentStatus(k)==='pending')return Number(state.settings.rentAmount||0);return 0}
function modal(title,html){document.getElementById('modal').innerHTML=`<div class="modalbg" id="mbg"><div class="modal"><div class="row"><h2>${esc(title)}</h2><button class="close" id="mclose">×</button></div>${html}</div></div>`;document.getElementById('mclose').onclick=closeModal;document.getElementById('mbg').onclick=e=>{if(e.target.id==='mbg')closeModal()}}function closeModal(){document.getElementById('modal').innerHTML=''}
function navigate(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(v).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render(v);scrollTo(0,0)}function render(v){if(v==='home')home();if(v==='history')history();if(v==='contract')contract();if(v==='documents')documents();if(v==='more')more()}